### ISSUE TITLE
Silence after playing the next song. 

### ISSUE THREAD

**Issue by ghost** [kurt-weber/hzswitch#2]
There seems to be a bug where after the next song starts playing, there is no sound. If I click on the time slider it the sound comes back but that is not a convenient fix since I have to do this for every song. The format of the songs is FLAC, if that helps in any way for a potential solution.

**Comment by kurt-weber** [comment]
Sorry nothing I can do about it. The same problem happened with mp3. The only dirty solution I found was stopping and start the playback at the beginning of each new track. This is already implemented though. It worked for mp3 but I am not sure why it won't do the trick for flac. In any case its a dirty fix because it makes the waitlist unusable. I am still hoping this bug fixes itself with a new release of rythmbox.

**Comment by kurt-weber** [comment]
This should be fixed now with the latest version.
